apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/user/k8s-deployments/mariadb-instance/data"
    type: DirectoryOrCreate
