apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  root-password: eW91cl9yb290X3Bhc3N3b3Jk
  database: eW91cl9kYXRhYmFzZV9uYW1l
  user: eW91cl9kYXRhYmFzZV91c2Vy
  password: eW91cl9kYXRhYmFzZV9wYXNzd29yZA==
