apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
data:
  my.cnf: |
    [mysqld]
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    
    # InnoDB settings
    innodb_buffer_pool_size = 256M
    innodb_log_file_size = 64M

    # Connection settings
    max_connections = 100

    # Binary log settings
    server_id = 1
    log_bin = mysql-bin
    binlog_format = ROW

    [client]
    default-character-set = utf8mb4
