apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.5-php8.1-apache
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "mariadb.default.svc.cluster.local:3306"
            - name: WORDPRESS_DB_NAME
              value: "wordpress"
            - name: WORDPRESS_DB_USER
              value: "wpuser"
            - name: WORDPRESS_DB_PASSWORD
              value: "wppassword"
          volumeMounts:
            - name: wp-content
              mountPath: /var/www/html
      volumes:
        - name: wp-content
          emptyDir: {}
